<a href="https://colab.research.google.com/github/harishraghavhr7/ML-models_numpy/blob/main/single_value_decomposition.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

a=np.array([
    [5,3,3],
    [4,3,2],
    [4,4,5]
],dtype=float)

In [ ]:
print(a)

[[5. 3. 3.]
 [4. 3. 2.]
 [4. 4. 5.]]


In [ ]:
U,S,VT=np.linalg.svd(a)

converting the singular values into diagonal matrix

In [ ]:
print(S)

[11.19065172  1.86886943  0.52596682]


In [ ]:
sigma = np.diag(S)

Reconstruction of matrix

In [ ]:
a_reconstructed=U @ sigma @ VT

In [ ]:
print(a_reconstructed)

[[5. 3. 3.]
 [4. 3. 2.]
 [4. 4. 5.]]


MOVIE_RATING_RECOMMENDATION

In [ ]:
import numpy as np

r=np.array([
    [5,3,np.nan],
    [4,np.nan,2],
    [np.nan,4,5]
],dtype=float)

r_org=r.copy()

In [ ]:
print(r_org)

[[ 5.  3. nan]
 [ 4. nan  2.]
 [nan  4.  5.]]


In [ ]:
col_means=np.nanmean(r,axis=0)

In [ ]:
print(col_means)

[4.5 3.5 3.5]


In [ ]:
inds=np.where(np.isnan(r))

In [ ]:
r[inds]=np.take(col_means,inds[1])

In [ ]:
print(r)

[[5.  3.  3.5]
 [4.  3.5 2. ]
 [4.5 4.  5. ]]


RECONSTRUCTION OF MATRIX

In [ ]:
U,S,VT=np.linalg.svd(r)

In [ ]:
re_diag=np.diag(S)

In [ ]:
a_reconstructed=U @ re_diag @ VT

In [ ]:
print(a_reconstructed)

[[5.  3.  3.5]
 [4.  3.5 2. ]
 [4.5 4.  5. ]]


In [ ]:
k = 2

U_k = U[:, :k]
S_k = np.diag(S[:k])
VT_k = VT[:k, :]

R_pred = U_k @ S_k @ VT_k

In [ ]:
print(R_pred)

[[4.60646694 3.55874237 3.44908118]
 [4.23430659 3.16732904 2.03031668]
 [4.67552491 3.75078789 5.02271098]]


In [ ]:
print(r_org)

[[ 5.  3. nan]
 [ 4. nan  2.]
 [nan  4.  5.]]


In [ ]:
missing_mask = np.isnan(r_org)

In [ ]:
predicted_values = R_pred[missing_mask]

print(predicted_values)

[3.44908118 3.16732904 4.67552491]
